### ISSUE TITLE
I run this on headless server and I got this error

### ISSUE THREAD

**Issue by mfaridi1394** [cvhariharan/debianbox#1]
I want made Debian 12 image by packer and I use your guide.
I want build this packer image on Debian server and Ubuntu server and I do not have GUI on this server.
When I run packer build command I get this error.
`024/05/05 16:44:36 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/05/05 16:44:36 Looking for available communicator (SSH, WinRM, etc) port between 2222 and 4444
==> debian-image.qemu.debian-qemu: Found port for communicator (SSH, WinRM, etc): 2361.
2024/05/05 16:44:36 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/05/05 16:44:36 Found available port: 2361 on IP: 127.0.0.1
==> debian-image.qemu.debian-qemu: Creating temporary RSA SSH key for instance...
==> debian-image.qemu.debian-qemu: Looking for available port between 5900 and 6000 on 127.0.0.1
2024/05/05 16:44:38 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/05/05 16:44:38 Looking for available port between 5900 and 6000 on 127.0.0.1
2024/05/05 16:44:38 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/05/05 16:44:38 Found available port: 5954 on IP: 127.0.0.1
2024/05/05 16:44:38 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/05/05 16:44:38 Found available VNC port: 5954 on IP: 127.0.0.1
2024/05/05 16:44:38 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/05/05 16:44:38 Qemu --version output: QEMU emulator version 7.2.9 (Debian 1:7.2+dfsg-7+deb12u5)
2024/05/05 16:44:38 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
2024/05/05 16:44:38 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/05/05 16:44:38 Qemu version: 7.2.9
==> debian-image.qemu.debian-qemu: Starting VM, booting from CD-ROM
2024/05/05 16:44:38 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/05/05 16:44:38 Qemu Builder has no floppy files, not attaching a floppy.
2024/05/05 16:44:38 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/05/05 16:44:38 Executing /usr/bin/qemu-system-x86_64: []string{"-boot", "once=d", "-machine", "type=pc,accel=kvm", "-vnc", "127.0.0.1:54", "-smp", "2", "-m", "4096M", "-netdev", "user,id=user.0,hostfwd=tcp::2361-:22", "-drive", "file=output-debian-qemu/debian-builder,if=virtio,cache=writeback,discard=ignore,format=qcow2", "-drive", "file=/home/mostafa/.cache/packer/9757e0a90306bc8a5d1c6921880c4cedf585fafa.iso,media=cdrom", "-name", "debian-builder", "-display", "gtk", "-device", "virtio-net,netdev=user.0"}
2024/05/05 16:44:38 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/05/05 16:44:38 Started Qemu. Pid: 3329371
2024/05/05 16:44:38 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/05/05 16:44:38 Qemu stderr: gtk initialization failed
==> debian-image.qemu.debian-qemu: Error launching VM: Qemu failed to start. Please run with PACKER_LOG=1 to get more info.
2024/05/05 16:44:38 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/05/05 16:44:38 failed to unlock port lockfile: close tcp 127.0.0.1:5954: use of closed network connection
2024/05/05 16:44:38 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/05/05 16:44:38 failed to unlock port lockfile: close tcp 127.0.0.1:2361: use of closed network connection
==> debian-image.qemu.debian-qemu: Deleting output directory...
2024/05/05 16:44:38 [INFO] (telemetry) ending qemu.debian-qemu
Build 'debian-image.qemu.debian-qemu' errored after 8 seconds 126 milliseconds: Build was halted.
`
I think it want start gtk.
I do not have gui on both server.
How I can fix this?

`024/05/05 13:41:10 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/05/05 13:41:10 Started Qemu. Pid: 176439
2024/05/05 13:41:10 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/05/05 13:41:10 Qemu stderr: qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
2024/05/05 13:41:10 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/05/05 13:41:10 Qemu stderr: qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
2024/05/05 13:41:10 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/05/05 13:41:10 Qemu stderr: gtk initialization failed
`

**Comment by cvhariharan** [comment]
Hi @mfaridi1394, you can use the `headless` option to build the image. By default packer tries to launch a GUI to show the console.

You can add it to `debianbox.pkr.hcl` in the `debian-qemu` source.

https://developer.hashicorp.com/packer/integrations/hashicorp/qemu/latest/components/builder/qemu

**Comment by mfaridi1394** [comment]
Thanks @cvhariharan 
Your guide save my life.
